// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzn-Br4adLb33F0QadfvCKZR1FebzyD_8',
    appId: '1:243651353100:web:d8d2c64928fd892d416c29',
    messagingSenderId: '243651353100',
    projectId: 'sastigaadi0',
    authDomain: 'sastigaadi0.firebaseapp.com',
    storageBucket: 'sastigaadi0.appspot.com',
    measurementId: 'G-VF5KBZQ96Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByuFdBo_hTCUigid6DnpiNQMXJ2umB3KI',
    appId: '1:243651353100:android:60ca4d61a77c6ff3416c29',
    messagingSenderId: '243651353100',
    projectId: 'sastigaadi0',
    storageBucket: 'sastigaadi0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfR9uUB-rqtLYWlJjpPIZbjP4iGi077uU',
    appId: '1:243651353100:ios:4b519bd9e6c5c881416c29',
    messagingSenderId: '243651353100',
    projectId: 'sastigaadi0',
    storageBucket: 'sastigaadi0.appspot.com',
    iosClientId:
        '243651353100-dbfkrbcaegtoh0icn809f4lgkq5nhmdc.apps.googleusercontent.com',
    iosBundleId: 'com.mavikdev.sastigaadi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfR9uUB-rqtLYWlJjpPIZbjP4iGi077uU',
    appId: '1:243651353100:ios:4b519bd9e6c5c881416c29',
    messagingSenderId: '243651353100',
    projectId: 'sastigaadi0',
    storageBucket: 'sastigaadi0.appspot.com',
    iosClientId:
        '243651353100-dbfkrbcaegtoh0icn809f4lgkq5nhmdc.apps.googleusercontent.com',
    iosBundleId: 'com.mavikdev.sastigaadi',
  );
}
